//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int BranchId { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string PhysAddress { get; set; }
        public string OpenClose { get; set; }
        public string PhoneNumber { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
